"""added moon model and moon bp

Revision ID: 24fffeb004c9
Revises: 574862c905d8
Create Date: 2023-05-09 12:00:07.225739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fffeb004c9'
down_revision = '574862c905d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planet', sa.Column('moon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    op.drop_table('moon')
    # ### end Alembic commands ###
